# Generated by Django 4.1.3 on 2022-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_skill_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_acnive',
            field=models.BooleanField(default=True),
        ),
    ]
