# Generated by Django 4.1.3 on 2022-11-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_rename_is_acnive_skill_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='create',
            new_name='created',
        ),
    ]
