# Generated by Django 4.1.3 on 2022-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_rename_create_vacancy_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
